image: Ubuntu
version: 1.0.{build}
services:
- docker
build_script:
  - sh: docker login -u $dockerhubuser -p $dockerhubpassword
  - sh: export CONTAINER_VERSION="natery2000/poe-aura-optimizer:${VERSION}"
  - sh: echo $CONTAINER_VERSION
  - sh: docker build -t $CONTAINER_VERSION .
  - sh: docker push $CONTAINER_VERSION
test: off